### ISSUE TITLE
Widget not showing when opening emails

### ISSUE THREAD

**Issue by distributev** [distributev/gmail-wordpress-mailchimp-integration#1]
Hi! following this I configured everything up to Part2: The WordPress Part - 

https://github.com/distributev/gmail-wordpress-mailchimp-integration 

I can see the widget was installed on top right apps panel - but when I open emails nothing happens - the widget does not show / activate at the bottom of emails

**Comment by mdkass** [comment]
Did you get the authorization screen when you clicked "Test installation flow"? and clicked Accept?

**Comment by mdkass** [comment]
Also what is your Gadget url, is it the same url I put "http://www.ispa-sa.com/gadget.xml" or a url hosted in another place?

**Comment by distributev** [comment]
Yes I got the authorization screen and I uploade the gadget.xml on my server - The gadget was installed I can see on top right of gmail apps. It's only that it's not showing when I open emails.

Can I check any console/debug what the error is?

**Comment by mdkass** [comment]
I read that the gadget could take few hours before it appears, and I experienced the same issue at first.
but are you sure the xml file is accessible when you put its url on your Internet browser?

**Comment by mdkass** [comment]
The problem is that you cant debug the gadget before the gadget title appears at the bottom of your emails, after that you can use the console to debug it.

**Comment by mdkass** [comment]
Also since you have my account password you can compare my gadget settings with yous and see what is missing or different.

**Comment by distributev** [comment]
It came - I just had to wait some time. I'll start testing now.
